<fieldset class="form-section submission-step" data-submission-step="2" hidden>
    <legend><span>02</span> <?= e(tr('Cerita & Nilai Inovasi', 'Innovation Story & Value')) ?></legend>
    <p class="submission-step__intro"><?= e(tr('Semua medan cerita warisan kekal di sini untuk memastikan draf dan data lama terus serasi.', 'All legacy story fields remain here so existing drafts and data stay compatible.')) ?></p>
    <label class="form-field"><span><?= e(tr('Tagline berorientasikan manfaat', 'Benefit-led tagline')) ?> <em>*</em></span><input type="text" name="tagline" value="<?= submission_value($submission, 'tagline') ?>" required maxlength="120" placeholder="<?= e(tr('Contoh: Kehadiran lebih pantas dan mudah dijejak.', 'Example: Faster attendance that is easier to trace.')) ?>"></label>
    <label class="form-field"><span><?= e(tr('Apakah masalah sebenar yang berlaku?', 'What real problem is occurring?')) ?> <em>*</em></span><textarea name="problem" rows="5" required minlength="30" maxlength="700" aria-describedby="problem-help"><?= submission_value($submission, 'problem') ?></textarea><small id="problem-help"><?= e(tr('Nyatakan siapa yang terkesan, keadaan semasa dan mengapa ia penting.', 'State who is affected, the current situation and why it matters.')) ?></small></label>
    <label class="form-field"><span><?= e(tr('Bagaimanakah projek menyelesaikan masalah itu?', 'How does the project solve the problem?')) ?> <em>*</em></span><textarea name="solution" rows="5" required minlength="30" maxlength="700"><?= submission_value($submission, 'solution') ?></textarea></label>
    <label class="form-field"><span><?= e(tr('Cara ia berfungsi', 'How it works')) ?> <em>*</em></span><textarea name="how_it_works" rows="4" required minlength="20" maxlength="600" placeholder="<?= e(tr('Terangkan aliran pengguna dalam beberapa langkah ringkas.', 'Explain the user flow in a few concise steps.')) ?>"><?= submission_value($submission, 'how_it_works') ?></textarea></label>
    <label class="form-field"><span><?= e(tr('Ciri utama', 'Key features')) ?></span><textarea name="features" rows="3" maxlength="500" placeholder="<?= e(tr('Satu ciri pada setiap baris.', 'One feature per line.')) ?>"><?= submission_value($submission, 'key_features') ?></textarea></label>
    <label class="form-field"><span><?= e(tr('Apakah hasil atau impak yang dijangka?', 'What outcome or impact is expected?')) ?> <em>*</em></span><textarea name="impact" rows="5" required minlength="20" maxlength="700"><?= submission_value($submission, 'impact') ?></textarea></label>
    <div class="form-row">
        <label class="form-field"><span><?= e(tr('Bukti yang tersedia', 'Available evidence')) ?></span><select name="evidence_status"><?php foreach ($evidenceOptions as $value => $label): ?><option value="<?= e($value) ?>" <?= ($submission['evidence_status'] ?? '') === $value ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></label>
        <label class="form-field"><span><?= e(tr('Teknologi / alat', 'Technologies / tools')) ?></span><input type="text" name="technologies" value="<?= submission_value($submission, 'technologies') ?>" placeholder="<?= e(tr('Contoh: Flutter, Firebase, QR Code', 'Example: Flutter, Firebase, QR Code')) ?>"></label>
    </div>
    <label class="form-field"><span><?= e(tr('Ringkasan bukti', 'Evidence summary')) ?></span><textarea name="evidence" rows="3" maxlength="500"><?= submission_value($submission, 'evidence_summary') ?></textarea></label>
    <label class="form-field"><span><?= e(tr('Pasukan dan peranan (data warisan)', 'Team and roles (legacy data)')) ?></span><textarea name="team" rows="3" maxlength="500"><?= submission_value($submission, 'team_details') ?></textarea></label>
    <label class="form-field"><span><?= e(tr('Perjalanan projek (data warisan)', 'Project journey (legacy data)')) ?></span><textarea name="journey" rows="3" maxlength="500"><?= submission_value($submission, 'project_journey') ?></textarea></label>
    <label class="form-field"><span><?= e(tr('Tindakan yang anda mahu daripada pelawat', 'Action you want visitors to take')) ?> <em>*</em></span><select name="call_to_action" required><option value=""><?= e(tr('Pilih tindakan utama', 'Select the primary action')) ?></option><?php foreach ($ctaOptions as $value => $label): ?><option value="<?= e($value) ?>" <?= ($submission['call_to_action'] ?? '') === $value ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></label>
</fieldset>
