<fieldset class="form-section submission-step" data-submission-step="4" hidden>
    <legend><span>04</span> <?= e(tr('Impak, Bukti & Anugerah', 'Impact, Evidence & Awards')) ?></legend>
    <div class="adaptive-category-notice" role="note">
        <strong><?= e(tr('Penyimpanan CP10C aktif', 'CP10C persistence enabled')) ?></strong>
        <p><?= e(tr('Metrik dan bukti diperlukan sebelum penghantaran semakan. Anugerah atau pengiktirafan boleh ditambah jika berkaitan.', 'Metrics and evidence are required before review submission. Awards or recognitions may be added when relevant.')) ?></p>
    </div>

    <section class="repeatable-section" data-repeatable="metrics">
        <header><div><p class="eyebrow"><?= e(tr('Koleksi 01', 'Collection 01')) ?></p><h2><?= e(tr('Metrik Impak', 'Impact Metrics')) ?></h2><p><?= e(tr('Gunakan nilai sebenar atau sasaran yang boleh difahami dan diukur.', 'Use an actual or target value that is understandable and measurable.')) ?></p></div><button class="button button--secondary" type="button" data-add-repeatable="metric"><?= e(tr('Tambah Metrik', 'Add Metric')) ?></button></header>
        <div class="repeatable-list" data-repeatable-list="metric">
            <?php $metricRows = $impactDetails['metrics'] ?: [[]]; foreach ($metricRows as $index => $metric): ?>
                <article class="repeatable-row" data-repeatable-row="metric">
                    <div class="repeatable-row__heading"><strong><?= e(tr('Metrik', 'Metric')) ?></strong><button type="button" data-remove-repeatable aria-label="<?= e(tr('Buang metrik', 'Remove metric')) ?>">×</button></div>
                    <div class="form-row"><label class="form-field"><span><?= e(tr('Nama metrik', 'Metric name')) ?> <em>*</em></span><input type="text" name="impact_metrics[<?= (int) $index ?>][label]" value="<?= e($metric['label'] ?? '') ?>" maxlength="180" required data-repeatable-field="label"></label><label class="form-field"><span><?= e(tr('Nilai semasa', 'Current value')) ?></span><input type="text" name="impact_metrics[<?= (int) $index ?>][value]" value="<?= e($metric['value'] ?? '') ?>" maxlength="120" data-repeatable-field="value"></label></div>
                    <div class="form-row"><label class="form-field"><span><?= e(tr('Unit', 'Unit')) ?></span><input type="text" name="impact_metrics[<?= (int) $index ?>][unit]" value="<?= e($metric['unit'] ?? '') ?>" maxlength="80" placeholder="%, orang, minit"></label><label class="form-field"><span><?= e(tr('Nilai asas', 'Baseline')) ?></span><input type="text" name="impact_metrics[<?= (int) $index ?>][baseline]" value="<?= e($metric['baseline'] ?? '') ?>" maxlength="120"></label></div>
                    <div class="form-row"><label class="form-field"><span><?= e(tr('Sasaran', 'Target')) ?></span><input type="text" name="impact_metrics[<?= (int) $index ?>][target]" value="<?= e($metric['target'] ?? '') ?>" maxlength="120" data-repeatable-field="target"></label><label class="form-field"><span><?= e(tr('Tarikh ukuran', 'Measurement date')) ?></span><input type="date" name="impact_metrics[<?= (int) $index ?>][measured_at]" value="<?= e($metric['measured_at'] ?? '') ?>"></label></div>
                    <label class="form-field"><span><?= e(tr('Nota sokongan metrik', 'Metric supporting notes')) ?></span><textarea name="impact_metrics[<?= (int) $index ?>][evidence_notes]" rows="2" maxlength="2000"><?= e($metric['evidence_notes'] ?? '') ?></textarea><small><?= e(tr('Setiap baris yang disimpan mesti mempunyai nama metrik.', 'Every stored row must have a metric name.')) ?></small></label>
                </article>
            <?php endforeach; ?>
        </div>
        <template data-repeatable-template="metric"><article class="repeatable-row" data-repeatable-row="metric"><div class="repeatable-row__heading"><strong><?= e(tr('Metrik', 'Metric')) ?></strong><button type="button" data-remove-repeatable aria-label="<?= e(tr('Buang metrik', 'Remove metric')) ?>">×</button></div><div class="form-row"><label class="form-field"><span><?= e(tr('Nama metrik', 'Metric name')) ?> <em>*</em></span><input type="text" name="impact_metrics[__INDEX__][label]" maxlength="180" required data-repeatable-field="label"></label><label class="form-field"><span><?= e(tr('Nilai semasa', 'Current value')) ?></span><input type="text" name="impact_metrics[__INDEX__][value]" maxlength="120" data-repeatable-field="value"></label></div><div class="form-row"><label class="form-field"><span><?= e(tr('Unit', 'Unit')) ?></span><input type="text" name="impact_metrics[__INDEX__][unit]" maxlength="80" placeholder="%, orang, minit"></label><label class="form-field"><span><?= e(tr('Nilai asas', 'Baseline')) ?></span><input type="text" name="impact_metrics[__INDEX__][baseline]" maxlength="120"></label></div><div class="form-row"><label class="form-field"><span><?= e(tr('Sasaran', 'Target')) ?></span><input type="text" name="impact_metrics[__INDEX__][target]" maxlength="120" data-repeatable-field="target"></label><label class="form-field"><span><?= e(tr('Tarikh ukuran', 'Measurement date')) ?></span><input type="date" name="impact_metrics[__INDEX__][measured_at]"></label></div><label class="form-field"><span><?= e(tr('Nota sokongan metrik', 'Metric supporting notes')) ?></span><textarea name="impact_metrics[__INDEX__][evidence_notes]" rows="2" maxlength="2000"></textarea><small><?= e(tr('Setiap baris yang disimpan mesti mempunyai nama metrik.', 'Every stored row must have a metric name.')) ?></small></label></article></template>
    </section>

    <section class="repeatable-section" data-repeatable="evidence">
        <header><div><p class="eyebrow"><?= e(tr('Koleksi 02', 'Collection 02')) ?></p><h2><?= e(tr('Bukti Impak', 'Impact Evidence')) ?></h2><p><?= e(tr('Gunakan pautan HTTP/HTTPS kepada laporan, data, borang maklum balas atau dokumentasi.', 'Use an HTTP/HTTPS link to a report, dataset, feedback form or documentation.')) ?></p></div><button class="button button--secondary" type="button" data-add-repeatable="evidence"><?= e(tr('Tambah Bukti', 'Add Evidence')) ?></button></header>
        <div class="repeatable-list" data-repeatable-list="evidence">
            <?php $evidenceRows = $impactDetails['evidence'] ?: [[]]; foreach ($evidenceRows as $index => $item): ?>
                <article class="repeatable-row" data-repeatable-row="evidence"><div class="repeatable-row__heading"><strong><?= e(tr('Bukti', 'Evidence')) ?></strong><button type="button" data-remove-repeatable aria-label="<?= e(tr('Buang bukti', 'Remove evidence')) ?>">×</button></div><label class="form-field"><span><?= e(tr('Tajuk bukti', 'Evidence title')) ?> <em>*</em></span><input type="text" name="impact_evidence[<?= (int) $index ?>][title]" value="<?= e($item['title'] ?? '') ?>" maxlength="255" required data-repeatable-field="title"></label><label class="form-field"><span><?= e(tr('Pautan bukti', 'Evidence URL')) ?> <em>*</em></span><input type="url" name="impact_evidence[<?= (int) $index ?>][url]" value="<?= e($item['url'] ?? '') ?>" maxlength="1000" placeholder="https://" required data-repeatable-field="url"></label><label class="form-field"><span><?= e(tr('Penerangan', 'Description')) ?></span><textarea name="impact_evidence[<?= (int) $index ?>][description]" rows="2" maxlength="2000"><?= e($item['description'] ?? '') ?></textarea></label></article>
            <?php endforeach; ?>
        </div>
        <template data-repeatable-template="evidence"><article class="repeatable-row" data-repeatable-row="evidence"><div class="repeatable-row__heading"><strong><?= e(tr('Bukti', 'Evidence')) ?></strong><button type="button" data-remove-repeatable aria-label="<?= e(tr('Buang bukti', 'Remove evidence')) ?>">×</button></div><label class="form-field"><span><?= e(tr('Tajuk bukti', 'Evidence title')) ?> <em>*</em></span><input type="text" name="impact_evidence[__INDEX__][title]" maxlength="255" required data-repeatable-field="title"></label><label class="form-field"><span><?= e(tr('Pautan bukti', 'Evidence URL')) ?> <em>*</em></span><input type="url" name="impact_evidence[__INDEX__][url]" maxlength="1000" placeholder="https://" required data-repeatable-field="url"></label><label class="form-field"><span><?= e(tr('Penerangan', 'Description')) ?></span><textarea name="impact_evidence[__INDEX__][description]" rows="2" maxlength="2000"></textarea></label></article></template>
    </section>

    <section class="repeatable-section" data-repeatable="recognitions">
        <header><div><p class="eyebrow"><?= e(tr('Koleksi 03', 'Collection 03')) ?></p><h2><?= e(tr('Anugerah & Pengiktirafan', 'Awards & Recognitions')) ?></h2><p><?= e(tr('Bahagian pilihan untuk pertandingan, pensijilan atau pengiktirafan rasmi.', 'Optional section for competitions, certifications or formal recognition.')) ?></p></div><button class="button button--secondary" type="button" data-add-repeatable="recognition"><?= e(tr('Tambah Pengiktirafan', 'Add Recognition')) ?></button></header>
        <div class="repeatable-list" data-repeatable-list="recognition">
            <?php foreach ($impactDetails['recognitions'] as $index => $recognition): ?>
                <article class="repeatable-row" data-repeatable-row="recognition"><div class="repeatable-row__heading"><strong><?= e(tr('Pengiktirafan', 'Recognition')) ?></strong><button type="button" data-remove-repeatable aria-label="<?= e(tr('Buang pengiktirafan', 'Remove recognition')) ?>">×</button></div><label class="form-field"><span><?= e(tr('Nama anugerah / pengiktirafan', 'Award / recognition title')) ?> <em>*</em></span><input type="text" name="recognitions[<?= (int) $index ?>][title]" value="<?= e($recognition['title'] ?? '') ?>" maxlength="255" required data-repeatable-field="title"></label><div class="form-row"><label class="form-field"><span><?= e(tr('Penganjur', 'Organiser')) ?></span><input type="text" name="recognitions[<?= (int) $index ?>][organiser]" value="<?= e($recognition['organiser'] ?? '') ?>" maxlength="255"></label><label class="form-field"><span><?= e(tr('Tahap / kategori', 'Level / category')) ?></span><input type="text" name="recognitions[<?= (int) $index ?>][level]" value="<?= e($recognition['level'] ?? '') ?>" maxlength="120"></label></div><div class="form-row"><label class="form-field"><span><?= e(tr('Tarikh', 'Date')) ?></span><input type="date" name="recognitions[<?= (int) $index ?>][award_date]" value="<?= e($recognition['award_date'] ?? '') ?>"></label><label class="form-field"><span><?= e(tr('Pautan bukti', 'Evidence URL')) ?></span><input type="url" name="recognitions[<?= (int) $index ?>][evidence_url]" value="<?= e($recognition['evidence_url'] ?? '') ?>" maxlength="500" placeholder="https://"></label></div><label class="form-field"><span><?= e(tr('Penerangan', 'Description')) ?></span><textarea name="recognitions[<?= (int) $index ?>][description]" rows="2" maxlength="2000"><?= e($recognition['description'] ?? '') ?></textarea></label></article>
            <?php endforeach; ?>
        </div>
        <template data-repeatable-template="recognition"><article class="repeatable-row" data-repeatable-row="recognition"><div class="repeatable-row__heading"><strong><?= e(tr('Pengiktirafan', 'Recognition')) ?></strong><button type="button" data-remove-repeatable aria-label="<?= e(tr('Buang pengiktirafan', 'Remove recognition')) ?>">×</button></div><label class="form-field"><span><?= e(tr('Nama anugerah / pengiktirafan', 'Award / recognition title')) ?> <em>*</em></span><input type="text" name="recognitions[__INDEX__][title]" maxlength="255" required data-repeatable-field="title"></label><div class="form-row"><label class="form-field"><span><?= e(tr('Penganjur', 'Organiser')) ?></span><input type="text" name="recognitions[__INDEX__][organiser]" maxlength="255"></label><label class="form-field"><span><?= e(tr('Tahap / kategori', 'Level / category')) ?></span><input type="text" name="recognitions[__INDEX__][level]" maxlength="120"></label></div><div class="form-row"><label class="form-field"><span><?= e(tr('Tarikh', 'Date')) ?></span><input type="date" name="recognitions[__INDEX__][award_date]"></label><label class="form-field"><span><?= e(tr('Pautan bukti', 'Evidence URL')) ?></span><input type="url" name="recognitions[__INDEX__][evidence_url]" maxlength="500" placeholder="https://"></label></div><label class="form-field"><span><?= e(tr('Penerangan', 'Description')) ?></span><textarea name="recognitions[__INDEX__][description]" rows="2" maxlength="2000"></textarea></label></article></template>
    </section>
</fieldset>
