<fieldset class="form-section submission-step" data-submission-step="6" hidden>
    <legend><span>06</span> <?= e(tr('Rekod Bimbingan Mentor', 'Mentor Guidance Records')) ?></legend>
    <div class="adaptive-category-notice" role="note">
        <strong><?= e(tr('Ringkas dan mudah', 'Short and simple')) ?></strong>
        <p><?= e(tr('Gunakan mentor daripada Bahagian 05. Tambah rekod hanya apabila ada bimbingan yang ingin direkodkan.', 'Use mentors from Section 05. Add a record only when there is guidance to capture.')) ?></p>
    </div>

    <section class="mentoring-editor">
        <header><div><h2><?= e(tr('Bimbingan yang diterima', 'Guidance received')) ?></h2><p><?= e(tr('Tiada tarikh, tempoh, skor atau penilaian teknikal diperlukan.', 'No dates, duration, scores, or technical ratings are required.')) ?></p></div><button class="button button--secondary" type="button" data-add-mentoring-record><?= e(tr('Tambah rekod bimbingan', 'Add guidance record')) ?></button></header>
        <div class="mentoring-editor__empty" data-mentoring-empty <?= $mentoringRecords ? 'hidden' : '' ?>><p><?= e(tr('Belum ada rekod bimbingan. Jika mentor belum ditambah, kembali ke Bahagian 05 dahulu.', 'No guidance records yet. If no mentor has been added, return to Section 05 first.')) ?></p></div>
        <div class="mentoring-editor__list" data-mentoring-list>
            <?php foreach ($mentoringRecords as $recordIndex => $record): $recordKey = $record['row_key'] ?? ('guidance-' . $recordIndex); ?>
                <article class="mentoring-card" data-mentoring-row>
                    <div class="mentoring-card__heading"><strong><?= e(tr('Rekod bimbingan', 'Guidance record')) ?></strong><button type="button" data-remove-mentoring aria-label="<?= e(tr('Buang rekod bimbingan', 'Remove guidance record')) ?>">×</button></div>
                    <input type="hidden" name="mentoring_records[<?= e($recordKey) ?>][id]" value="<?= (int) ($record['id'] ?? 0) ?>">
                    <div class="form-row">
                        <label class="form-field"><span><?= e(tr('Mentor', 'Mentor')) ?> <em>*</em></span><select name="mentoring_records[<?= e($recordKey) ?>][mentor_reference]" required data-mentor-select><option value=""><?= e(tr('Pilih mentor', 'Select mentor')) ?></option><?php foreach ($participantDetails['mentors'] as $mentor): $mentorReference = !empty($mentor['id']) ? 'id:' . $mentor['id'] : 'ref:' . $mentor['row_key']; ?><option value="<?= e($mentorReference) ?>" <?= ($record['mentor_reference'] ?? '') === $mentorReference ? 'selected' : '' ?>><?= e($mentor['full_name']) ?></option><?php endforeach; ?></select></label>
                        <label class="form-field"><span><?= e(tr('Bentuk bimbingan', 'Guidance format')) ?></span><select name="mentoring_records[<?= e($recordKey) ?>][guidance_type]"><option value=""><?= e(tr('Pilih jika berkaitan', 'Select if relevant')) ?></option><?php foreach ($guidanceTypeOptions as $value => $label): ?><option value="<?= e($value) ?>" <?= ($record['guidance_type'] ?? '') === $value ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></label>
                    </div>
                    <label class="form-field"><span><?= e(tr('Apa yang dibimbing?', 'What guidance was provided?')) ?> <em>*</em></span><textarea name="mentoring_records[<?= e($recordKey) ?>][guidance_focus]" rows="3" maxlength="2000" required placeholder="<?= e(tr('Contoh: semakan idea, pembangunan prototaip, dokumentasi atau pembentangan.', 'Example: idea review, prototype development, documentation, or presentation.')) ?>"><?= e($record['guidance_focus'] ?? '') ?></textarea></label>
                    <label class="form-field"><span><?= e(tr('Hasil bimbingan', 'Guidance outcome')) ?> <em>*</em></span><textarea name="mentoring_records[<?= e($recordKey) ?>][guidance_outcome]" rows="3" maxlength="2000" required placeholder="<?= e(tr('Contoh: fungsi aplikasi ditambah baik, laporan diperbetulkan atau pembentangan menjadi lebih jelas.', 'Example: application features improved, the report was corrected, or the presentation became clearer.')) ?>"><?= e($record['guidance_outcome'] ?? '') ?></textarea></label>
                </article>
            <?php endforeach; ?>
        </div>
        <template data-mentoring-template><article class="mentoring-card" data-mentoring-row><div class="mentoring-card__heading"><strong><?= e(tr('Rekod bimbingan', 'Guidance record')) ?></strong><button type="button" data-remove-mentoring aria-label="<?= e(tr('Buang rekod bimbingan', 'Remove guidance record')) ?>">×</button></div><input type="hidden" name="mentoring_records[__KEY__][id]" value="0"><div class="form-row"><label class="form-field"><span><?= e(tr('Mentor', 'Mentor')) ?> <em>*</em></span><select name="mentoring_records[__KEY__][mentor_reference]" required data-mentor-select><option value=""><?= e(tr('Pilih mentor', 'Select mentor')) ?></option></select></label><label class="form-field"><span><?= e(tr('Bentuk bimbingan', 'Guidance format')) ?></span><select name="mentoring_records[__KEY__][guidance_type]"><option value=""><?= e(tr('Pilih jika berkaitan', 'Select if relevant')) ?></option><?php foreach ($guidanceTypeOptions as $value => $label): ?><option value="<?= e($value) ?>"><?= e($label) ?></option><?php endforeach; ?></select></label></div><label class="form-field"><span><?= e(tr('Apa yang dibimbing?', 'What guidance was provided?')) ?> <em>*</em></span><textarea name="mentoring_records[__KEY__][guidance_focus]" rows="3" maxlength="2000" required placeholder="<?= e(tr('Contoh: semakan idea, pembangunan prototaip, dokumentasi atau pembentangan.', 'Example: idea review, prototype development, documentation, or presentation.')) ?>"></textarea></label><label class="form-field"><span><?= e(tr('Hasil bimbingan', 'Guidance outcome')) ?> <em>*</em></span><textarea name="mentoring_records[__KEY__][guidance_outcome]" rows="3" maxlength="2000" required placeholder="<?= e(tr('Contoh: fungsi aplikasi ditambah baik, laporan diperbetulkan atau pembentangan menjadi lebih jelas.', 'Example: application features improved, the report was corrected, or the presentation became clearer.')) ?>"></textarea></label></article></template>
    </section>
</fieldset>
