<fieldset class="form-section submission-step" data-submission-step="5" hidden>
    <legend><span>05</span> <?= e(tr('Peserta / Inovator', 'Participants / Innovators')) ?></legend>
    <div class="adaptive-category-notice" role="note">
        <strong><?= e(tr('Penyimpanan CP10D aktif', 'CP10D persistence enabled')) ?></strong>
        <p><?= e(tr('Tambah pelajar dan mentor, tetapkan ketua pasukan, susun rekod, dan muat naik foto profil.', 'Add students and mentors, assign the team leader, reorder records, and upload profile photos.')) ?></p>
    </div>

    <section class="people-editor" data-people-editor="student">
        <header><div><p class="eyebrow"><?= e(tr('Jenis Individu 01', 'Person Type 01')) ?></p><h2><?= e(tr('Pelajar', 'Students')) ?></h2><p><?= e(tr('Sekurang-kurangnya seorang pelajar diperlukan sebelum penghantaran semakan.', 'At least one student is required before review submission.')) ?></p></div><button class="button button--secondary" type="button" data-add-person="student"><?= e(tr('Tambah Pelajar', 'Add Student')) ?></button></header>
        <div class="people-editor__list" data-person-list="student">
            <?php $studentRows = $participantDetails['students'] ?: [['row_key' => 'student-initial']]; foreach ($studentRows as $studentIndex => $student): $studentKey = $student['row_key'] ?? ('student-' . $studentIndex); $studentPhoto = submission_profile_photo_public_path($student['profile_image_path'] ?? null); ?>
                <article class="person-editor-card" data-person-row="student">
                    <div class="person-editor-card__toolbar"><strong><?= e(tr('Pelajar', 'Student')) ?></strong><div><button type="button" data-move-person="up" aria-label="<?= e(tr('Alih ke atas', 'Move up')) ?>">↑</button><button type="button" data-move-person="down" aria-label="<?= e(tr('Alih ke bawah', 'Move down')) ?>">↓</button><button type="button" data-remove-person aria-label="<?= e(tr('Buang pelajar', 'Remove student')) ?>">×</button></div></div>
                    <input type="hidden" name="participants[<?= e($studentKey) ?>][id]" value="<?= (int) ($student['id'] ?? 0) ?>">
                    <div class="person-editor-card__layout">
                        <div class="profile-photo-editor">
                            <div class="profile-photo-editor__preview" data-photo-preview><?= $studentPhoto ? '<img src="' . e($studentPhoto) . '" alt="">' : '<span aria-hidden="true">+</span>' ?></div>
                            <label class="form-field"><span><?= e(tr('Foto profil', 'Profile photo')) ?></span><input type="file" name="participant_photos[<?= e($studentKey) ?>]" accept="image/jpeg,image/png,image/webp" data-photo-input><small><?= e(tr('JPG, PNG atau WebP, maksimum 5MB. Foto akan dicrop 1:1 dan disimpan maksimum 512×512.', 'JPG, PNG or WebP, maximum 5MB. The photo will be cropped 1:1 and stored at up to 512×512.')) ?></small></label>
                            <?php if ($studentPhoto): ?><label class="form-check form-check--compact"><input type="checkbox" name="participants[<?= e($studentKey) ?>][remove_photo]" value="1"><span><?= e(tr('Padam foto semasa', 'Remove current photo')) ?></span></label><?php endif; ?>
                        </div>
                        <div class="person-editor-card__fields">
                            <div class="form-row"><label class="form-field"><span><?= e(tr('Nama penuh', 'Full name')) ?> <em>*</em></span><input type="text" name="participants[<?= e($studentKey) ?>][full_name]" value="<?= e($student['full_name'] ?? '') ?>" maxlength="160" required data-person-required></label><label class="form-field"><span><?= e(tr('Program', 'Programme')) ?> <em>*</em></span><select name="participants[<?= e($studentKey) ?>][programme]" required data-person-required><option value=""><?= e(tr('Pilih program', 'Select programme')) ?></option><?php foreach ($studentProgrammeOptions as $code => $label): ?><option value="<?= e($code) ?>" <?= ($student['programme'] ?? '') === $code ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></label></div>
                            <div class="form-row"><label class="form-field"><span><?= e(tr('Nama kelas', 'Class name')) ?> <em>*</em></span><input type="text" name="participants[<?= e($studentKey) ?>][class_name]" value="<?= e($student['class_name'] ?? '') ?>" maxlength="120" required data-person-required placeholder="<?= e(tr('Contoh: 2DVM KPD, 1DVM KMK, 2SVM BAK', 'Example: 2DVM KPD, 1DVM KMK, 2SVM BAK')) ?>"></label><label class="form-field"><span><?= e(tr('Tahun pengajian', 'Year of study')) ?> <em>*</em></span><select name="participants[<?= e($studentKey) ?>][year_of_study]" required data-person-required><option value=""><?= e(tr('Pilih tahun', 'Select year')) ?></option><?php foreach ($studyYearOptions as $value => $label): ?><option value="<?= e($value) ?>" <?= ($student['year_of_study'] ?? '') === $value ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></label></div>
                            <label class="form-field"><span><?= e(tr('Peranan dalam projek', 'Project role')) ?> <em>*</em></span><input type="text" name="participants[<?= e($studentKey) ?>][role_title]" value="<?= e($student['role_title'] ?? '') ?>" maxlength="160" required data-person-required placeholder="<?= e(tr('Contoh: Pembangun utama, pereka produk', 'Example: Lead developer, product designer')) ?>"></label>
                            <label class="form-check"><input type="checkbox" name="participants[<?= e($studentKey) ?>][is_team_leader]" value="1" data-team-leader <?= !empty($student['is_team_leader']) ? 'checked' : '' ?>><span><?= e(tr('Ketua pasukan', 'Team leader')) ?></span></label>
                        </div>
                    </div>
                </article>
            <?php endforeach; ?>
        </div>
        <template data-person-template="student"><article class="person-editor-card" data-person-row="student"><div class="person-editor-card__toolbar"><strong><?= e(tr('Pelajar', 'Student')) ?></strong><div><button type="button" data-move-person="up" aria-label="<?= e(tr('Alih ke atas', 'Move up')) ?>">↑</button><button type="button" data-move-person="down" aria-label="<?= e(tr('Alih ke bawah', 'Move down')) ?>">↓</button><button type="button" data-remove-person aria-label="<?= e(tr('Buang pelajar', 'Remove student')) ?>">×</button></div></div><input type="hidden" name="participants[__KEY__][id]" value="0"><div class="person-editor-card__layout"><div class="profile-photo-editor"><div class="profile-photo-editor__preview" data-photo-preview><span aria-hidden="true">+</span></div><label class="form-field"><span><?= e(tr('Foto profil', 'Profile photo')) ?></span><input type="file" name="participant_photos[__KEY__]" accept="image/jpeg,image/png,image/webp" data-photo-input><small><?= e(tr('JPG, PNG atau WebP, maksimum 5MB. Crop 1:1, maksimum 512×512.', 'JPG, PNG or WebP, maximum 5MB. 1:1 crop, maximum 512×512.')) ?></small></label></div><div class="person-editor-card__fields"><div class="form-row"><label class="form-field"><span><?= e(tr('Nama penuh', 'Full name')) ?> <em>*</em></span><input type="text" name="participants[__KEY__][full_name]" maxlength="160" required data-person-required></label><label class="form-field"><span><?= e(tr('Program', 'Programme')) ?> <em>*</em></span><select name="participants[__KEY__][programme]" required data-person-required><option value=""><?= e(tr('Pilih program', 'Select programme')) ?></option><?php foreach ($studentProgrammeOptions as $code => $label): ?><option value="<?= e($code) ?>"><?= e($label) ?></option><?php endforeach; ?></select></label></div><div class="form-row"><label class="form-field"><span><?= e(tr('Nama kelas', 'Class name')) ?> <em>*</em></span><input type="text" name="participants[__KEY__][class_name]" maxlength="120" required data-person-required placeholder="<?= e(tr('Contoh: 2DVM KPD', 'Example: 2DVM KPD')) ?>"></label><label class="form-field"><span><?= e(tr('Tahun pengajian', 'Year of study')) ?> <em>*</em></span><select name="participants[__KEY__][year_of_study]" required data-person-required><option value=""><?= e(tr('Pilih tahun', 'Select year')) ?></option><?php foreach ($studyYearOptions as $value => $label): ?><option value="<?= e($value) ?>"><?= e($label) ?></option><?php endforeach; ?></select></label></div><label class="form-field"><span><?= e(tr('Peranan dalam projek', 'Project role')) ?> <em>*</em></span><input type="text" name="participants[__KEY__][role_title]" maxlength="160" required data-person-required></label><label class="form-check"><input type="checkbox" name="participants[__KEY__][is_team_leader]" value="1" data-team-leader><span><?= e(tr('Ketua pasukan', 'Team leader')) ?></span></label></div></div></article></template>
    </section>

    <section class="people-editor" data-people-editor="mentor">
        <header><div><p class="eyebrow"><?= e(tr('Jenis Individu 02', 'Person Type 02')) ?></p><h2><?= e(tr('Mentor', 'Mentors')) ?></h2><p><?= e(tr('Mentor adalah pilihan tetapi setiap rekod yang ditambah perlu lengkap.', 'Mentors are optional, but every added record must be complete.')) ?></p></div><button class="button button--secondary" type="button" data-add-person="mentor"><?= e(tr('Tambah Mentor', 'Add Mentor')) ?></button></header>
        <div class="people-editor__list" data-person-list="mentor">
            <?php foreach ($participantDetails['mentors'] as $mentorIndex => $mentor): $mentorKey = $mentor['row_key'] ?? ('mentor-' . $mentorIndex); $mentorPhoto = submission_profile_photo_public_path($mentor['profile_image_path'] ?? null); ?>
                <article class="person-editor-card" data-person-row="mentor"><div class="person-editor-card__toolbar"><strong><?= e(tr('Mentor', 'Mentor')) ?></strong><div><button type="button" data-move-person="up" aria-label="<?= e(tr('Alih ke atas', 'Move up')) ?>">↑</button><button type="button" data-move-person="down" aria-label="<?= e(tr('Alih ke bawah', 'Move down')) ?>">↓</button><button type="button" data-remove-person aria-label="<?= e(tr('Buang mentor', 'Remove mentor')) ?>">×</button></div></div><input type="hidden" name="mentors[<?= e($mentorKey) ?>][id]" value="<?= (int) ($mentor['id'] ?? 0) ?>"><div class="person-editor-card__layout"><div class="profile-photo-editor"><div class="profile-photo-editor__preview" data-photo-preview><?= $mentorPhoto ? '<img src="' . e($mentorPhoto) . '" alt="">' : '<span aria-hidden="true">+</span>' ?></div><label class="form-field"><span><?= e(tr('Foto profil', 'Profile photo')) ?></span><input type="file" name="mentor_photos[<?= e($mentorKey) ?>]" accept="image/jpeg,image/png,image/webp" data-photo-input><small><?= e(tr('JPG, PNG atau WebP, maksimum 5MB. Crop 1:1, maksimum 512×512.', 'JPG, PNG or WebP, maximum 5MB. 1:1 crop, maximum 512×512.')) ?></small></label><?php if ($mentorPhoto): ?><label class="form-check form-check--compact"><input type="checkbox" name="mentors[<?= e($mentorKey) ?>][remove_photo]" value="1"><span><?= e(tr('Padam foto semasa', 'Remove current photo')) ?></span></label><?php endif; ?></div><div class="person-editor-card__fields"><div class="form-row"><label class="form-field"><span><?= e(tr('Nama penuh', 'Full name')) ?> <em>*</em></span><input type="text" name="mentors[<?= e($mentorKey) ?>][full_name]" value="<?= e($mentor['full_name'] ?? '') ?>" maxlength="160" required data-person-required></label><label class="form-field"><span><?= e(tr('Jawatan', 'Position')) ?> <em>*</em></span><input type="text" name="mentors[<?= e($mentorKey) ?>][position_title]" value="<?= e($mentor['position_title'] ?? '') ?>" maxlength="180" required data-person-required></label></div><label class="form-field"><span><?= e(tr('Organisasi', 'Organisation')) ?> <em>*</em></span><input type="text" name="mentors[<?= e($mentorKey) ?>][institution]" value="<?= e($mentor['institution'] ?? '') ?>" maxlength="255" required data-person-required></label><label class="form-field"><span><?= e(tr('Peranan dalam projek', 'Project role')) ?> <em>*</em></span><textarea name="mentors[<?= e($mentorKey) ?>][role_title]" rows="2" maxlength="2000" required data-person-required><?= e($mentor['role_title'] ?? '') ?></textarea></label></div></div></article>
            <?php endforeach; ?>
        </div>
        <template data-person-template="mentor"><article class="person-editor-card" data-person-row="mentor"><div class="person-editor-card__toolbar"><strong><?= e(tr('Mentor', 'Mentor')) ?></strong><div><button type="button" data-move-person="up" aria-label="<?= e(tr('Alih ke atas', 'Move up')) ?>">↑</button><button type="button" data-move-person="down" aria-label="<?= e(tr('Alih ke bawah', 'Move down')) ?>">↓</button><button type="button" data-remove-person aria-label="<?= e(tr('Buang mentor', 'Remove mentor')) ?>">×</button></div></div><input type="hidden" name="mentors[__KEY__][id]" value="0"><div class="person-editor-card__layout"><div class="profile-photo-editor"><div class="profile-photo-editor__preview" data-photo-preview><span aria-hidden="true">+</span></div><label class="form-field"><span><?= e(tr('Foto profil', 'Profile photo')) ?></span><input type="file" name="mentor_photos[__KEY__]" accept="image/jpeg,image/png,image/webp" data-photo-input><small><?= e(tr('JPG, PNG atau WebP, maksimum 5MB. Crop 1:1, maksimum 512×512.', 'JPG, PNG or WebP, maximum 5MB. 1:1 crop, maximum 512×512.')) ?></small></label></div><div class="person-editor-card__fields"><div class="form-row"><label class="form-field"><span><?= e(tr('Nama penuh', 'Full name')) ?> <em>*</em></span><input type="text" name="mentors[__KEY__][full_name]" maxlength="160" required data-person-required></label><label class="form-field"><span><?= e(tr('Jawatan', 'Position')) ?> <em>*</em></span><input type="text" name="mentors[__KEY__][position_title]" maxlength="180" required data-person-required></label></div><label class="form-field"><span><?= e(tr('Organisasi', 'Organisation')) ?> <em>*</em></span><input type="text" name="mentors[__KEY__][institution]" maxlength="255" required data-person-required></label><label class="form-field"><span><?= e(tr('Peranan dalam projek', 'Project role')) ?> <em>*</em></span><textarea name="mentors[__KEY__][role_title]" rows="2" maxlength="2000" required data-person-required></textarea></label></div></div></article></template>
    </section>
</fieldset>
