<?php
require_once __DIR__.'/includes/bootstrap.php';require_once __DIR__.'/includes/public-ui.php';
$pageTitle=tr('Tentang HubInovasi','About HubInovasi');$activePage='about';enable_public_mockup('mockup-about');
require __DIR__.'/includes/header.php';
?>
<main id="main-content" class="pm-shell"><div class="container">
 <section class="about-launch"><div><span class="pm-kicker"><?= e(tr('TENTANG HUBINOVASI','ABOUT HUBINOVASI')) ?></span><h1 class="pm-display"><?= tr('Platform pelancaran idea pelajar dengan <em>potensi dunia sebenar.</em>','A launchpad for student ideas with <em>real-world potential.</em>') ?></h1><p class="pm-lead"><?= e(tr('HubInovasi KVKS mengubah projek pelajar menjadi kisah inovasi yang menarik—membantu pengunjung memahami masalah, penyelesaian, manusia, impak dan tindakan seterusnya di sebalik setiap idea.','HubInovasi KVKS transforms student projects into compelling innovation stories, helping visitors understand the problem, solution, people, impact and next action behind every idea.')) ?></p></div><div class="about-collage"><div class="about-collage__team" aria-label="<?= e(tr('Komuniti inovator HubInovasi','HubInovasi innovator community')) ?>"><img src="assets/images/home/innovator-aiman.webp" alt=""><img src="assets/images/home/innovator-syazwanie.webp" alt=""><img src="assets/images/home/innovator-jason.webp" alt=""><img src="assets/images/home/innovator-vania.webp" alt=""></div><div class="about-collage__journey pm-card"><strong><?= e(tr('Perjalanan HubInovasi','The HubInovasi Journey')) ?></strong><div><span>♢<br><?= e(tr('Bina Idea','Build Idea')) ?></span><span>⇧<br><?= e(tr('Hantar','Submit')) ?></span><span>↗<br><?= e(tr('Bentuk Pitch','Shape Pitch')) ?></span><span>▣<br><?= e(tr('Pamer','Showcase')) ?></span><span>♡<br><?= e(tr('Cipta Impak','Create Impact')) ?></span></div></div><div class="about-collage__impact pm-card"><span><?= e(tr('Impak Dicipta','Impact Created')) ?></span><strong>2.8K+</strong><small><?= e(tr('Kehidupan disentuh secara positif','Lives positively impacted')) ?></small></div></div></section>
 <section class="about-ownership pm-card" aria-labelledby="about-ownership-title">
  <div class="about-ownership__hub"><img src="assets/images/branding/hubinovasi-kvks-primary.png" alt="HubInovasi KVKS — <?= e(tr('Platform Inovasi Pelajar','Student Innovation Platform')) ?>"></div>
  <span class="about-ownership__divider" aria-hidden="true"></span>
  <div class="about-ownership__institution"><span id="about-ownership-title"><?= e(tr('Sebuah inisiatif rasmi oleh','An official initiative by')) ?></span><img src="assets/images/branding/kvks-official.png" alt="Kolej Vokasional Kuala Selangor"><p><?= e(tr('HubInovasi ialah platform inovasi pelajar Kolej Vokasional Kuala Selangor yang mempamerkan penyelesaian, proses pembangunan dan impak projek secara tersusun.','HubInovasi is Kolej Vokasional Kuala Selangor’s student innovation platform for presenting project solutions, development journeys and impact in a structured way.')) ?></p></div>
 </section>
 <section class="why-grid"><div><div class="pm-section-title"><h2><?= e(tr('Mengapa HubInovasi diwujudkan','Why HubInovasi exists')) ?></h2></div><div class="why-cards"><?php foreach([['book',tr('Kisah Produk','Product Story'),tr('Membantu pelajar menceritakan inovasi mereka dengan jelas.','Help students tell their innovation story clearly.')],['target',tr('Keyakinan Visual','Visual Confidence'),tr('Reka bentuk yang baik membina perhatian dan kepercayaan.','Great design earns attention and trust.')],['globe',tr('Relevan Dunia Sebenar','Real-World Relevance'),tr('Menghubungkan penyelesaian dengan masalah yang boleh diukur.','Connect solutions to measurable problems.')],['star',tr('Kebanggaan & Keterlihatan','Pride & Visibility'),tr('Meraikan inovator dan pencapaian mereka.','Celebrate innovators and achievements.')]] as $x): ?><article class="pm-card"><span class="pm-icon"><?= ui_icon($x[0]) ?></span><h3><?= e($x[1]) ?></h3><p><?= e($x[2]) ?></p></article><?php endforeach; ?></div></div><div><div class="pm-section-title"><h2><?= e(tr('Cara ia berfungsi','How it works')) ?></h2></div><div class="how-row"><?php foreach([['bulb',tr('Bina idea','Build an idea')],['rocket',tr('Hantar projek','Submit a project')],['book',tr('Bentuk kisah pitch','Shape the pitch story')],['chart',tr('Pamer penyelesaian','Showcase the solution')],['people',tr('Hubungkan untuk impak','Connect for impact')]] as $i=>$x): ?><div class="how-step"><span class="pm-icon <?= $i%2?'orange':'' ?>"><?= ui_icon($x[0]) ?></span><b><?= $i+1 ?></b><strong><?= e($x[1]) ?></strong><p><?= e(tr('Bawa idea ke langkah seterusnya.','Move the idea to its next stage.')) ?></p></div><?php endforeach; ?></div></div></section>
 <section class="about-mid"><div class="submission-check pm-card"><h2><?= e(tr('Apakah ciri penghantaran yang kukuh?','What makes a strong submission?')) ?></h2><?php foreach([tr('Masalah dunia sebenar yang jelas','Clear real-world problem'),tr('Cara penyelesaian berfungsi','Practical solution and how it works'),tr('Screenshot atau mockup produk yang kukuh','Strong screenshots or product mockups'),tr('Bukti impak atau rintis yang jujur','Honest impact or pilot evidence'),tr('Pasukan dan mentor yang dapat dikenal pasti','Visible team and mentor')] as $x): ?><p><?= e($x) ?></p><?php endforeach; ?><div><strong><?= e(tr('Perlukan bantuan sebelum menghantar?','Need help before submitting?')) ?></strong><p><?= e(tr('Panduan kami menerangkan keperluan dan contoh.','Our guide explains requirements and examples.')) ?></p><a class="pm-btn primary" href="submit-project.php"><?= e(tr('BACA PANDUAN','READ GUIDE')) ?> →</a></div></div><div class="about-community-visual"><img src="assets/images/home/about-community.webp" width="1600" height="1000" alt="<?= e(tr('Komuniti pelajar HubInovasi KVKS berbincang dan membangunkan projek inovasi','HubInovasi KVKS student community discussing and developing innovation projects')) ?>"></div><div class="snapshot"><?php foreach([['rocket','48+',tr('Projek Dipamerkan','Projects Showcased')],['people','120+',tr('Inovator Pelajar','Student Innovators')],['award','15+',tr('Anugerah & Pengiktirafan','Awards & Recognition')],['heart','10+',tr('Rakan Industri / Komuniti','Industry / Community Partners')]] as $x): ?><div class="pm-card"><span class="pm-icon" style="margin:auto"><?= ui_icon($x[0]) ?></span><strong><?= e($x[1]) ?></strong><span><?= e($x[2]) ?></span></div><?php endforeach; ?></div></section>
 <section class="about-bottom"><div class="faq"><h2><?= e(tr('Soalan lazim','Frequently asked questions')) ?></h2><?php foreach([[tr('Siapa boleh menghantar projek?','Who can submit a project?'),tr('Pelajar dan pasukan KVKS dengan maklumat projek yang boleh disahkan.','KVKS students and teams with verifiable project information.')],[tr('Adakah produk perlu siap?','Do I need a finished product?'),tr('Tidak. Prototaip yang jelas dan bukti kemajuan juga boleh dipertimbangkan.','No. A clear prototype and evidence of progress can also be considered.')],[tr('Bolehkah projek dikemas kini kemudian?','Can I update my project later?'),tr('Ya. Projek boleh ditambah baik selepas semakan.','Yes. Projects can be improved after review.')]] as $x): ?><details><summary><?= e($x[0]) ?></summary><p><?= e($x[1]) ?></p></details><?php endforeach; ?></div><div class="contact-block" id="contact"><h2><?= e(tr('Hubungi kami','Get in touch')) ?></h2><p><?= e(tr('Kami di sini untuk menyokong perjalanan inovasi anda.','We are here to support your innovation journey.')) ?></p><div class="contact-grid"><div class="pm-card"><strong>⌖ Kolej Vokasional Kuala Selangor</strong><p>Jalan Vocational, 45000 Kuala Selangor, Selangor</p></div><div class="pm-card"><strong>✉ hubinovasi@kvks.edu.my</strong><p><?= e(tr('Untuk penghantaran dan kolaborasi rasmi.','For official submissions and collaboration.')) ?></p></div><div class="pm-card"><strong>☏ +60 3-3299 1234</strong><p><?= e(tr('Isnin–Jumaat, 9:00–5:00','Mon–Fri, 9:00–5:00')) ?></p></div></div></div></section>
 <section class="launch-banner"><div><h2><?= e(tr('Bersedia melancarkan idea anda?','Ready to launch your idea?')) ?></h2><p><?= e(tr('Mulakan penghantaran projek atau hubungi pasukan HubInovasi.','Start your project submission or connect with the HubInovasi team.')) ?></p></div><a class="pm-btn primary" href="submit-project.php"><?= e(tr('Hantar Projek','Submit Project')) ?> ↗</a><a class="pm-btn" href="#contact"><?= e(tr('Hubungi Kami','Contact Us')) ?> →</a></section>
</div></main>
<?php require __DIR__.'/includes/footer.php'; ?>
