<?php
require_once __DIR__.'/includes/bootstrap.php';require_once __DIR__.'/includes/public-ui.php';
$pageTitle=tr('Pertandingan & Impak','Competitions & Impact');$activePage='impact';enable_public_mockup('mockup-impact');
$competitions=[
 ['16–17<br>SEP 2026','Innovation Fest 2026',tr('Mempamerkan inovasi pelajar terbaik daripada kolej vokasional seluruh negara.','Showcasing the best student innovations from vocational colleges nationwide.'),tr('Dewan Bestari, KVKS','Dewan Bestari, KVKS'),'competition-innovation-fest.webp'],
 ['10–12<br>OCT 2026','TVET Innovation Challenge 2026',tr('Mengangkat kecemerlangan TVET melalui inovasi dan penyelesaian teknologi.','Driving TVET excellence through innovation and technology solutions.'),'Putrajaya International Convention Centre','competition-tvet-challenge.webp'],
 ['20–22<br>NOV 2026','ASEAN Youth Innovation Summit',tr('Memperkasa inovator muda untuk menghasilkan impak melangkaui sempadan.','Empowering young innovators to create impact beyond borders.'),'Kuala Lumpur, Malaysia','competition-asean-summit.webp'],
];
require __DIR__.'/includes/header.php';
?>
<main id="main-content" class="pm-shell"><div class="container">
 <nav class="pm-breadcrumbs"><a href="index.php"><?= e(tr('Utama','Home')) ?></a><span>›</span><strong><?= e(tr('Pertandingan & Impak','Competitions & Impact')) ?></strong></nav>
 <section class="impact-hero"><div><h1 class="pm-display"><?= tr('Pertandingan.<br>Impak Yang <em>Bermakna.</em>','Competitions.<br>Impact That <em>Matters.</em>') ?></h1><p class="pm-lead"><?= e(tr('Kami mempamerkan inovasi pelajar, meraikan pencapaian dan mengukur impak sebenar idea dalam tindakan.','We showcase student innovations, celebrate achievements and measure the real impact of ideas in action.')) ?></p></div><div class="trophy-art" aria-hidden="true"></div><aside class="impact-stats"><div><strong>15+</strong><span><?= e(tr('Anugerah Dimenangi','Awards Won')) ?></span></div><div><strong style="color:var(--pm-orange)">10+</strong><span><?= e(tr('Pertandingan Disertai','Competitions Joined')) ?></span></div><div><strong>4</strong><span><?= e(tr('Pengiktirafan Nasional / Antarabangsa','National / International Recognitions')) ?></span></div></aside></section>
 <section class="impact-main"><div><div class="pm-section-title"><h2><?= e(tr('PERTANDINGAN AKAN DATANG','UPCOMING COMPETITIONS')) ?></h2><a href="#"><?= e(tr('Lihat semua pertandingan','View all competitions')) ?> →</a></div><div class="competition-grid"><?php foreach($competitions as $c): ?><article class="competition-card pm-card"><div class="competition-art"><img src="assets/images/home/<?= e($c[4]) ?>" width="1600" height="900" alt="<?= e($c[1]) ?>"><time><?= $c[0] ?></time></div><div class="competition-card__body"><h3><?= e($c[1]) ?></h3><p><?= e($c[2]) ?></p><p>⌖ <?= e($c[3]) ?></p><a class="pm-section-title" style="margin:0;color:var(--pm-pink);font-size:.72rem;text-decoration:none" href="#"><span><?= e(tr('Kebangsaan','National')) ?></span><strong><?= e(tr('BUTIRAN','DETAILS')) ?> →</strong></a></div></article><?php endforeach; ?></div></div>
  <aside><div class="pm-section-title"><h2><?= e(tr('SOROTAN IMPAK','IMPACT HIGHLIGHTS')) ?></h2><a href="#"><?= e(tr('Laporan penuh','Full report')) ?> →</a></div><div class="impact-highlights"><?php foreach([['people','12,340+',tr('Kehidupan Disentuh','Lives Impacted')],['leaf','6.8 TON',tr('Impak Alam Sekitar','Environmental Impact')],['book','580+',tr('Pelajar Diperkasa','Students Empowered')],['chart','35+',tr('Projek dalam Tindakan','Projects in Action')]] as $i=>$x): ?><article class="impact-highlight pm-card"><span class="pm-icon <?= $i%2?'orange':'' ?>"><?= ui_icon($x[0]) ?></span><strong><?= e($x[1]) ?></strong><b><?= e($x[2]) ?></b><p><?= e(tr('Bukti impak melalui projek yang diuji dalam persekitaran sebenar.','Evidence of impact through projects tested in real settings.')) ?></p></article><?php endforeach; ?></div></aside></section>
 <section class="pm-ribbon pm-card"><div><h2><?= tr('Idea besar layak mendapat <em style="color:var(--pm-pink);font-style:normal">pentas lebih besar.</em>','Big ideas deserve a <em style="color:var(--pm-pink);font-style:normal">bigger stage.</em>') ?></h2><p><?= e(tr('Sertai pertandingan, raih pengiktirafan dan hasilkan impak yang berkekalan.','Join competitions, gain recognition and create impact that lasts.')) ?></p><p style="margin-top:12px"><a class="pm-btn primary" href="submit-project.php"><?= e(tr('HANTAR PROJEK ANDA','SUBMIT YOUR PROJECT')) ?> ↗</a></p></div><?php foreach([['award',tr('Dapatkan Pengiktirafan','Get Recognised')],['people',tr('Kembangkan Rangkaian','Grow Your Network')],['rocket',tr('Hasilkan Impak Sebenar','Create Real Impact')],['award',tr('Bina Masa Hadapan','Build Your Future')]] as $x): ?><div><span class="pm-icon"><?= ui_icon($x[0]) ?></span><strong><?= e($x[1]) ?></strong><p><?= e(tr('Bina portfolio, jaringan dan peluang baharu melalui inovasi.','Build your portfolio, network and new opportunities through innovation.')) ?></p></div><?php endforeach; ?></section>
</div></main>
<?php require __DIR__.'/includes/footer.php'; ?>
