<?php
require_once __DIR__ . '/includes/project-repository.php';
require_once __DIR__ . '/includes/public-ui.php';
$slug = trim((string)($_GET['slug'] ?? ''));
$project = $slug !== '' ? get_public_project_by_slug($slug) : null;
$pageTitle = $project ? $project['name'] : tr('Projek Tidak Dijumpai','Project Not Found');
$activePage = 'areas';
enable_public_mockup('mockup-project');
$visible = $project && !empty($project['detail_available']);
$programmeSummary = $project ? implode(', ', $project['programmes'] ?? []) : '';
$primaryCollaborator = $project['collaborators'][0]['name'] ?? '';
$publishedMedia = $project['submission_media'] ?? ['gallery'=>[], 'video_url'=>'', 'milestones'=>[]];
$problemVisuals = array_values(array_filter($publishedMedia['problem_visual'] ?? [], static fn (array $item): bool => submission_gallery_public_path($item['file_path'] ?? null) !== null));
$solutionVisuals = array_values(array_filter($publishedMedia['solution_visual'] ?? [], static fn (array $item): bool => submission_gallery_public_path($item['file_path'] ?? null) !== null));
$publishedMedia['gallery'] = array_values(array_filter($publishedMedia['gallery'] ?? [], static fn (array $item): bool => submission_gallery_public_path($item['file_path'] ?? null) !== null));
$publishedPosters = array_values(array_filter($publishedMedia['poster'] ?? [], static fn (array $item): bool => submission_gallery_public_path($item['file_path'] ?? null) !== null));
$projectPoster = $publishedPosters[0] ?? null;
$publishedMetrics = $project['submission_impact']['metrics'] ?? [];
$videoEmbedUrl = submission_video_embed_url($publishedMedia['video_url'] ?? '');
$publishedCover = '';
foreach ($publishedMedia['gallery'] as $galleryImage) if (!empty($galleryImage['is_cover']) && submission_gallery_public_path($galleryImage['file_path'] ?? null)) { $publishedCover = $galleryImage['file_path']; break; }
function pm_text($value): string { if(is_array($value)) return (string)($value['text'] ?? $value['title'] ?? implode(' ',array_filter($value,'is_string'))); return (string)$value; }
require __DIR__ . '/includes/header.php';


// DURIAN_RADAR_FORCE_IMAGE
if (($slug ?? ($_GET['slug'] ?? '')) === 'durian-radar') {
    if (isset($project) && is_array($project)) {
        $project['application_screenshot'] =
            'assets/images/projects/durian-radar-main.png?v=' .
            filemtime(__DIR__ . '/assets/images/projects/durian-radar-main.png');

        $project['image'] =
            'assets/images/projects/durian-radar-main.png?v=' .
            filemtime(__DIR__ . '/assets/images/projects/durian-radar-main.png');

        $project['hero_image'] =
            'assets/images/projects/durian-radar-main.png?v=' .
            filemtime(__DIR__ . '/assets/images/projects/durian-radar-main.png');
    }
}



?>
<main id="main-content" class="pm-shell"><div class="container">
 <?php if($visible): ?>
  <nav class="pm-breadcrumbs"><a href="index.php"><?= e(tr('Utama','Home')) ?></a><span>›</span><a href="explore.php"><?= e(tr('Penyelesaian','Solutions')) ?></a><span>›</span><strong><?= e($project['name']) ?></strong></nav>
  <section class="detail-hero">
   <div class="detail-copy"><span class="pm-kicker"><?= e(tr('INOVASI','INNOVATION')) ?></span><h1 class="pm-display"><?= e($project['name']) ?></h1><p class="pm-lead"><?= e($project['tagline']) ?></p><div class="detail-meta"><?php if($programmeSummary): ?><span>♙ <?= e(tr('Program peneraju: ','Lead programme: ').$programmeSummary) ?></span><?php endif; ?><?php if($primaryCollaborator): ?><span>♢ <?= e(tr('Rakan kolaborasi: ','Collaborator: ').$primaryCollaborator) ?></span><?php endif; ?><span><?= e($project['innovation_type']) ?></span><span class="pm-kicker"><?= e($project['status']) ?></span></div><div class="detail-actions"><a class="pm-btn primary" href="#story"><?= e(tr('LIHAT PITCH','VIEW PITCH')) ?> ↗</a><?php if($project['links']): ?><a class="pm-btn" href="<?= e($project['links'][0]['url']) ?>" target="_blank" rel="noopener"><?= e(tr('DEMO LANGSUNG','LIVE DEMO')) ?> ↗</a><?php endif; ?><a class="pm-btn" href="#technology"><?= e(tr('TEKNOLOGI','TECHNOLOGY')) ?> ↓</a></div></div>
   <div class="detail-hero__visual"><div class="detail-device"><img src="<?= e($publishedCover ?: project_detail_image($project)) ?>" alt="<?= e(tr('Pratonton projek ','Project preview ').$project['name']) ?>"></div></div>
  </section>
  <section class="story-stack" id="story">
   <article class="story-row pm-card<?= !$problemVisuals && !$project['problem_points'] ? ' story-row--text-only' : '' ?>"><div class="story-index"><strong>01</strong><span class="pm-icon"><?= ui_icon('bulb') ?></span></div><div class="story-title"><h2><?= e(tr('Masalah','Problem')) ?></h2><p><?= e($project['problem']) ?></p></div><?php if ($problemVisuals): ?><div class="story-media story-media--<?= count($problemVisuals) > 1 ? 'collage' : 'single' ?>"><?php foreach ($problemVisuals as $visual): $path = submission_gallery_public_path($visual['file_path'] ?? null); if (!$path) continue; ?><figure><img src="<?= e($path) ?>" alt="<?= e($visual['caption'] ?: tr('Visual masalah projek','Project problem visual')) ?>"><?php if ($visual['caption']): ?><figcaption><?= e($visual['caption']) ?></figcaption><?php endif; ?></figure><?php endforeach; ?></div><?php elseif ($project['problem_points']): ?><div class="story-content"><?php foreach(array_slice($project['problem_points'],0,3) as $i=>$point): ?><div><strong><?= ['3×',tr('Lewat','Late'),tr('Terhad','Limited')][$i] ?? '•' ?></strong><span><?= e(pm_text($point)) ?></span></div><?php endforeach; ?></div><?php endif; ?></article>
   <article class="story-row pm-card<?= !$solutionVisuals && !$project['solution_points'] ? ' story-row--text-only' : '' ?>"><div class="story-index"><strong style="background:var(--pm-orange)">02</strong><span class="pm-icon orange"><?= ui_icon('target') ?></span></div><div class="story-title"><h2><?= e(tr('Penyelesaian','Solution')) ?></h2><p><?= e($project['solution']) ?></p></div><?php if ($solutionVisuals): ?><div class="story-media story-media--<?= count($solutionVisuals) > 1 ? 'collage' : 'single' ?>"><?php foreach ($solutionVisuals as $visual): $path = submission_gallery_public_path($visual['file_path'] ?? null); if (!$path) continue; ?><figure><img src="<?= e($path) ?>" alt="<?= e($visual['caption'] ?: tr('Visual penyelesaian projek','Project solution visual')) ?>"><?php if ($visual['caption']): ?><figcaption><?= e($visual['caption']) ?></figcaption><?php endif; ?></figure><?php endforeach; ?></div><?php elseif ($project['solution_points']): ?><div class="story-content"><?php foreach(array_slice($project['solution_points'],0,4) as $point): ?><div><span class="pm-icon orange"><?= ui_icon('shield') ?></span><span><?= e(pm_text($point)) ?></span></div><?php endforeach; ?></div><?php endif; ?></article>
   <article class="story-row pm-card<?= !$project['process_steps'] ? ' story-row--text-only' : '' ?>"><div class="story-index"><strong>03</strong><span class="pm-icon"><?= ui_icon('code') ?></span></div><div class="story-title"><h2><?= e(tr('Cara Ia Berfungsi','How It Works')) ?></h2><?php if (!$project['process_steps']): ?><p><?= e(tr('Aliran projek diterangkan dalam bahagian penyelesaian.', 'The project flow is explained in the solution section.')) ?></p><?php endif; ?></div><?php if ($project['process_steps']): ?><div class="story-content journey-line"><?php foreach(array_slice($project['process_steps'],0,5) as $step): ?><span><?= e(pm_text($step)) ?></span><?php endforeach; ?></div><?php endif; ?></article>
   <div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:12px" class="detail-triptych">
    <article class="story-row pm-card" style="grid-template-columns:88px 1fr"><div class="story-index"><strong style="background:var(--pm-orange)">04</strong><span class="pm-icon orange"><?= ui_icon('star') ?></span></div><div class="story-title"><h2><?= e(tr('Ciri Utama','Key Features')) ?></h2><ul class="story-list"><?php foreach(array_slice($project['features'],0,6) as $x): ?><li><?= e(pm_text($x)) ?></li><?php endforeach; ?></ul></div></article>
    <article class="story-row pm-card" style="grid-template-columns:88px 1fr"><div class="story-index"><strong>05</strong><span class="pm-icon"><?= ui_icon('target') ?></span></div><div class="story-title"><h2><?= e(tr('Impak','Impact')) ?></h2><p><?= e($project['impact']) ?></p><?php if ($publishedMetrics): ?><div class="published-kpis"><?php foreach (array_slice($publishedMetrics,0,4) as $metric): ?><article><strong><?= e(($metric['value'] ?: $metric['target']) ?: '—') ?><?= $metric['unit'] ? ' ' . e($metric['unit']) : '' ?></strong><span><?= e($metric['label']) ?></span></article><?php endforeach; ?></div><?php else: ?><ul class="story-list"><?php foreach(array_slice($project['impact_points'],0,4) as $x): ?><li><?= e(pm_text($x)) ?></li><?php endforeach; ?></ul><?php endif; ?></div></article>
    <article class="story-row pm-card" id="technology" style="grid-template-columns:88px 1fr"><div class="story-index"><strong style="background:var(--pm-orange)">06</strong><span class="pm-icon orange"><?= ui_icon('code') ?></span></div><div class="story-title"><h2><?= e(tr('Teknologi','Technology')) ?></h2><ul class="pm-tags"><?php foreach(array_slice($project['technology_stack'],0,8) as $x): ?><li><?= e(pm_text($x)) ?></li><?php endforeach; ?></ul></div></article>
   </div>
   <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px" class="detail-duo">
    <article class="story-row pm-card" style="grid-template-columns:88px 1fr"><div class="story-index"><strong>07</strong><span class="pm-icon"><?= ui_icon('people') ?></span></div><div class="story-title"><h2><?= e(tr('Pasukan & Kolaborasi','Team & Collaboration')) ?></h2><?php $publishedPeople = $project['submission_people'] ?? ['students'=>[],'mentors'=>[]]; if ($publishedPeople['students'] || $publishedPeople['mentors']): ?><div class="published-people"><?php foreach ($publishedPeople['students'] as $person): ?><article class="published-person<?= $person['is_team_leader'] ? ' published-person--leader' : '' ?>"><?php if ($photo = submission_profile_photo_public_path($person['profile_image_path'] ?? null)): ?><img src="<?= e($photo) ?>" alt="<?= e(tr('Foto profil ', 'Profile photo of ') . $person['full_name']) ?>"><?php endif; ?><div><?php if ($person['is_team_leader']): ?><span><?= e(tr('Ketua Pasukan','Team Leader')) ?></span><?php endif; ?><strong><?= e($person['full_name']) ?></strong><small><?= e($person['programme']) ?> · <?= e($person['class_name']) ?> · <?= e($person['year_of_study']) ?></small><p><?= e($person['role_title']) ?></p></div></article><?php endforeach; ?><?php foreach ($publishedPeople['mentors'] as $person): ?><article class="published-person"><?php if ($photo = submission_profile_photo_public_path($person['profile_image_path'] ?? null)): ?><img src="<?= e($photo) ?>" alt="<?= e(tr('Foto profil ', 'Profile photo of ') . $person['full_name']) ?>"><?php endif; ?><div><span><?= e(tr('Mentor','Mentor')) ?></span><strong><?= e($person['full_name']) ?></strong><small><?= e($person['position_title']) ?> · <?= e($person['institution']) ?></small><p><?= e($person['role_title']) ?></p></div></article><?php endforeach; ?></div><?php elseif($project['team']): foreach($project['team'] as $person): ?><p><strong><?= e($person['full_name']) ?></strong><br><?= e($person['role_title'] ?: tr('Ahli Pasukan','Team Member')) ?></p><?php endforeach; else: ?><p><?= e(tr('Maklumat ahli pasukan sedang disahkan.','Team member information is being verified.')) ?></p><?php endif; ?><?php foreach($project['collaborators'] as $collaborator): ?><div class="project-collaborator"><span><?= e(tr('Rakan Kolaborasi','Collaborator')) ?></span><strong><?= e($collaborator['name']) ?></strong><p><?= e($collaborator['role_description']) ?></p></div><?php endforeach; ?></div></article>
    <article class="story-row pm-card" style="grid-template-columns:88px 1fr"><div class="story-index"><strong style="background:var(--pm-orange)">08</strong><span class="pm-icon orange"><?= ui_icon('pin') ?></span></div><div class="story-title"><h2><?= e(tr('Perjalanan Projek','Project Journey')) ?></h2><div class="published-timeline"><?php if ($publishedMedia['milestones']): foreach(array_slice($publishedMedia['milestones'],0,10) as $x): ?><article><span></span><div><strong><?= e($x['title']) ?></strong><p><?= e($x['description']) ?></p></div></article><?php endforeach; else: foreach(array_slice($project['journey_milestones'],0,5) as $x): ?><article><span></span><div><p><?= e(pm_text($x)) ?></p></div></article><?php endforeach; endif; ?></div></div></article>
   </div>
   <?php if ($projectPoster && ($posterPath = submission_gallery_public_path($projectPoster['file_path'] ?? null))): ?><section class="project-poster-card pm-card"><div><span class="pm-kicker">🖼️ <?= e(tr('POSTER PROJEK','PROJECT POSTER')) ?></span><?php if ($projectPoster['caption']): ?><p><?= e($projectPoster['caption']) ?></p><?php endif; ?></div><img src="<?= e($posterPath) ?>" alt="<?= e($projectPoster['caption'] ?: tr('Poster projek','Project poster')) ?>"></section><?php endif; ?>
   <?php if ($publishedMedia['gallery'] || submission_video_url_is_valid($publishedMedia['video_url'])): ?><section class="pm-card project-gallery-section"><span class="pm-kicker">📷 <?= e(tr('GALERI PROJEK','PROJECT GALLERY')) ?></span><?php if ($publishedMedia['gallery']): ?><div class="published-gallery"><?php foreach ($publishedMedia['gallery'] as $image): $path = submission_gallery_public_path($image['file_path'] ?? null); if (!$path) continue; ?><figure><img src="<?= e($path) ?>" alt="<?= e($image['caption'] ?: tr('Gambar projek ', 'Project image ') . $project['name']) ?>"><?php if ($image['caption']): ?><figcaption><?= e($image['caption']) ?></figcaption><?php endif; ?></figure><?php endforeach; ?></div><?php endif; ?><?php if ($videoEmbedUrl): ?><div class="published-video-embed"><iframe src="<?= e($videoEmbedUrl) ?>" title="<?= e(tr('Video demo projek','Project demo video')) ?>" loading="lazy" allow="accelerometer; autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe></div><?php endif; ?><?php if (submission_video_url_is_valid($publishedMedia['video_url'])): ?><p class="published-gallery-video"><a class="pm-btn primary" href="<?= e($publishedMedia['video_url']) ?>" target="_blank" rel="noopener noreferrer"><?= e(tr('TONTON VIDEO DEMO','WATCH DEMO VIDEO')) ?> ↗</a></p><?php endif; ?></section><?php endif; ?>
   <section class="detail-cta pm-card"><div><span class="pm-kicker">09 · <?= e(tr('SERUAN TINDAKAN','CALL TO ACTION')) ?></span><h2><?= e(tr('Mari bina penyelesaian yang lebih bermakna bersama.','Let’s build more meaningful solutions together.')) ?></h2><p><?= e($project['short_description']) ?></p></div><div class="detail-actions"><a class="pm-btn primary" href="about.php#contact"><?= e(tr('HUBUNGI PASUKAN','CONTACT TEAM')) ?> ✉</a><a class="pm-btn" href="explore.php"><?= e(tr('KONGSI','SHARE')) ?> ↗</a></div></section>
  </section>
 <?php else: ?><section style="padding:100px 0;text-align:center"><span class="pm-kicker"><?= e(tr('PROJEK','PROJECT')) ?></span><h1 class="pm-display"><?= e(tr('Kisah projek sedang disediakan.','Project story is being prepared.')) ?></h1><p class="pm-lead" style="margin-inline:auto"><?= e(tr('Kembali ke katalog untuk meneroka penyelesaian lain.','Return to the catalogue to explore other solutions.')) ?></p><p><a class="pm-btn primary" href="explore.php"><?= e(tr('Teroka Projek','Explore Projects')) ?></a></p></section><?php endif; ?>
</div></main>
<?php require __DIR__ . '/includes/footer.php'; ?>
